"""Shared utilities, dependency injection factories, and UI helpers for Investiga CLI."""

from scripts.common.console import (
    INVESTIGA_THEME,
    GracefulExit,
    create_progress,
    get_console,
    print_banner,
    print_error,
    print_info,
    print_key_values,
    print_section,
    print_success,
    print_warning,
    setup_signal_handling,
)
from scripts.common.factory import (
    build_cli_bm25_index_async,
    create_cli_benchmark,
    create_cli_embedding_service,
    create_cli_etl_service,
    create_cli_evaluator,
    create_cli_rag_service,
    create_cli_retrieval_service,
    create_cli_vector_repository,
    get_cli_db_session,
    get_cli_settings,
)
from scripts.common.helpers import (
    bootstrap_environment,
    format_bytes,
    format_duration,
    format_ms,
    format_pct,
    format_score,
    resolve_path,
)

__all__ = [
    "INVESTIGA_THEME",
    "GracefulExit",
    "bootstrap_environment",
    "build_cli_bm25_index_async",
    "create_cli_benchmark",
    "create_cli_embedding_service",
    "create_cli_etl_service",
    "create_cli_evaluator",
    "create_cli_rag_service",
    "create_cli_retrieval_service",
    "create_cli_vector_repository",
    "create_progress",
    "format_bytes",
    "format_duration",
    "format_ms",
    "format_pct",
    "format_score",
    "get_cli_db_session",
    "get_cli_settings",
    "get_console",
    "print_banner",
    "print_error",
    "print_info",
    "print_key_values",
    "print_section",
    "print_success",
    "print_warning",
    "resolve_path",
    "setup_signal_handling",
]
